import { auth } from '@/auth';
import { db } from '@/lib/db';
import { createBridge } from '@/lib/bridge';
import { NextRequest, NextResponse } from 'next/server';

/**
 * POST /api/bridge/create
 * Create a new bridge session from Facebook lead/question + lawyer advice.
 *
 * Body:
 *   question   string   — the Facebook question or client inquiry (immutable)
 *   answer     string   — the lawyer's initial advice/response   (immutable)
 *
 * Notes:
 *   - Both fields are stored as the bridge's IMMUTABLE Source of Truth.
 *     Once created, no code path may overwrite them — enforced by Prisma
 *     middleware in lib/db.ts. See plan §1B for rationale.
 *   - shortCode (8 chars) and conversationId (32 chars, opaque resume key)
 *     are server-generated by lib/bridge.createBridge().
 */
export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const profile = await db.lawyerProfile.findUnique({
      where: { userId: session.user.id },
      select: { id: true },
    });
    if (!profile) {
      return NextResponse.json({ error: 'LawyerProfile not found' }, { status: 404 });
    }

    const body = await req.json();
    const { question, answer } = body;

    if (!question || typeof question !== 'string' || !question.trim()) {
      return NextResponse.json(
        { error: 'question is required and must be a non-empty string' },
        { status: 400 }
      );
    }
    if (!answer || typeof answer !== 'string' || !answer.trim()) {
      return NextResponse.json(
        { error: 'answer is required and must be a non-empty string' },
        { status: 400 }
      );
    }

    const bridge = await createBridge({
      profileId: profile.id,
      initialQuestion: question,
      initialAnswer: answer,
      createdBy: 'lawyer',
    });

    return NextResponse.json({
      success: true,
      bridgeId: bridge.id,
      shortCode: bridge.shortCode,
    });
  } catch (error) {
    console.error('Bridge creation error:', error);
    return NextResponse.json({ error: 'Failed to create bridge' }, { status: 500 });
  }
}
